### ISSUE TITLE
Win with sinking destroyer and battleship and hitting the minesweeper once

### ISSUE THREAD

**Issue by HaruVON** [cs361fall2018/project-team-35#78]
Upon sinking destroyer and battleship, once the minesweeper is hit once it ends the game with your victory.

**Comment by HaruVON** [comment]
Successfully recreated this bug. I'll make a video of it and post it so everyone knows what I'm seeing.

**Comment by dillanea** [comment]
Just to confirm @HaruVON , the minesweeper should sink on one hit if the captain's quarter is hit once. So, if it is a bug, I assume hitting the non cq part of the minesweeper should cause it to sink.
