### ISSUE TITLE
Sinking a ship by hitting the captain's quarters doesn't update the rest of the ship to sunk

### ISSUE THREAD

**Issue by HaruVON** [cs361fall2018/project-team-35#79]
Upon sinking a ship via captain's quarters, the other squares associated with the ship that haven't been hit aren't updated to sunk status

**Comment by dillanea** [comment]
No, once the captains quarter's is hit, it will send that signal to the game. If we wanted to, the back end will have to get all the ship squares associated with the captain's quarters, set them all to hit, and give the captain's quarter either a sunk or cqsunk status.

**Comment by dillanea** [comment]
That way the front end will act like those squares were hit and mark them accordingly
